### ISSUE TITLE
Outline design by wireframe

### ISSUE THREAD

**Issue by joycewu37** [CMU-313/fall-2021-hw2-hammer#2]
(title, description, etc.)

8 hours

Other frontend form tasks depend on initial wireframe design. This task can be independent of initial repo setup. This is where the idea slowly transitions to the physical website, and tasks can be reviewed to be more detailed and other tasks can be added to the list if necessary.

**Comment by michellejli77** [comment]
https://www.figma.com/file/fjZ7zQ3fFLX0zpS3pslCfZ/hammer?node-id=312%3A

[wireframe.pdf](https://github.com/CMU-313/fall-2021-hw2-hammer/files/7189232/wireframe.pdf)
