### ISSUE TITLE
Create way to upload documents (resume)

### ISSUE THREAD

**Issue by joycewu37** [CMU-313/fall-2021-hw2-hammer#5]
2 hours

Depends on Basic UI Structure. This functionality will be adding a `onclick` function to the predefined “Upload” button setup in the Basic structure task. Therefore, looking up the upload functionality and implementing this one function will take up to 2 hours. We would also need to specify the file type to .pdf and maybe some other options.

**Comment by michellejli77** [comment]
Decided on Slack that reviewers will not need to upload resumes, that is mostly the applicants job
