### ISSUE TITLE
Save results (to backend/db)

### ISSUE THREAD

**Issue by joycewu37** [CMU-313/fall-2021-hw2-hammer#9]
2 hours

Depends on data being aggregated and compiled into a human-readable format before it can be stored in the database. The 2 hours would be used to navigate small dependencies and inevitable errors with data formatting and saving.

**Comment by AlexanderChiuy** [comment]
By adding `SingleObjectCreateView` to the ResumeCreateView class, Mayan already has a way of saving the form data to the relevant model which is Resume in our case (in the generics.py file)
